[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
getset = "0.1.6"
raw-window-handle = "0.6.2"
thiserror = "2.0.16"
winit = "0.30.12"
