[package]
name = "renderers"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
ash = "0.38.0"
ash-window = "0.13.0"
bytemuck.workspace = true
glam.workspace = true
gpu-allocator = "0.28.0"
hashbrown.workspace = true
log.workspace = true
naga.workspace = true
ron.workspace = true
serde.workspace = true
wgpu = "30.0.1"
winit.workspace = true
